apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: course-end-deployment
  name: course-end-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-end-deployment
    template:
    metadata:
      labels:
        app: course-end-deployment
    spec:
      containers:
      - image: mritdock8765/course-end-image:v1
        name: course-end-image
